/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SectionsRouteImport } from './routes/sections'
import { Route as R404RouteImport } from './routes/$404'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProfileIndexRouteImport } from './routes/profile/index'
import { Route as NewsIndexRouteImport } from './routes/news/index'
import { Route as EventsIndexRouteImport } from './routes/events/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as ProfileUpcomingRouteImport } from './routes/profile/upcoming'
import { Route as NewsIdRouteImport } from './routes/news/$id'
import { Route as EventsIdRouteImport } from './routes/events/$id'
import { Route as AuthRegisterRouteImport } from './routes/auth/register'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AdminUsersIndexRouteImport } from './routes/admin/users/index'
import { Route as AdminNewsIndexRouteImport } from './routes/admin/news/index'
import { Route as AdminEventsIndexRouteImport } from './routes/admin/events/index'
import { Route as AdminApplicationsIndexRouteImport } from './routes/admin/applications/index'
import { Route as AdminNewsNewRouteImport } from './routes/admin/news/new'
import { Route as AdminEventsNewRouteImport } from './routes/admin/events/new'
import { Route as AdminNewsIdEditRouteImport } from './routes/admin/news/$id.edit'
import { Route as AdminEventsIdEditRouteImport } from './routes/admin/events/$id.edit'

const SectionsRoute = SectionsRouteImport.update({
  id: '/sections',
  path: '/sections',
  getParentRoute: () => rootRouteImport,
} as any)
const R404Route = R404RouteImport.update({
  id: '/$404',
  path: '/$404',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileIndexRoute = ProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsIndexRoute = NewsIndexRouteImport.update({
  id: '/news/',
  path: '/news/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsIndexRoute = EventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const ProfileUpcomingRoute = ProfileUpcomingRouteImport.update({
  id: '/profile/upcoming',
  path: '/profile/upcoming',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsIdRoute = NewsIdRouteImport.update({
  id: '/news/$id',
  path: '/news/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsIdRoute = EventsIdRouteImport.update({
  id: '/events/$id',
  path: '/events/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersIndexRoute = AdminUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminNewsIndexRoute = AdminNewsIndexRouteImport.update({
  id: '/news/',
  path: '/news/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminEventsIndexRoute = AdminEventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminApplicationsIndexRoute = AdminApplicationsIndexRouteImport.update({
  id: '/applications/',
  path: '/applications/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminNewsNewRoute = AdminNewsNewRouteImport.update({
  id: '/news/new',
  path: '/news/new',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminEventsNewRoute = AdminEventsNewRouteImport.update({
  id: '/events/new',
  path: '/events/new',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminNewsIdEditRoute = AdminNewsIdEditRouteImport.update({
  id: '/news/$id/edit',
  path: '/news/$id/edit',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminEventsIdEditRoute = AdminEventsIdEditRouteImport.update({
  id: '/events/$id/edit',
  path: '/events/$id/edit',
  getParentRoute: () => AdminRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/$404': typeof R404Route
  '/sections': typeof SectionsRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/events/$id': typeof EventsIdRoute
  '/news/$id': typeof NewsIdRoute
  '/profile/upcoming': typeof ProfileUpcomingRoute
  '/admin/': typeof AdminIndexRoute
  '/events/': typeof EventsIndexRoute
  '/news/': typeof NewsIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/admin/events/new': typeof AdminEventsNewRoute
  '/admin/news/new': typeof AdminNewsNewRoute
  '/admin/applications/': typeof AdminApplicationsIndexRoute
  '/admin/events/': typeof AdminEventsIndexRoute
  '/admin/news/': typeof AdminNewsIndexRoute
  '/admin/users/': typeof AdminUsersIndexRoute
  '/admin/events/$id/edit': typeof AdminEventsIdEditRoute
  '/admin/news/$id/edit': typeof AdminNewsIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$404': typeof R404Route
  '/sections': typeof SectionsRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/events/$id': typeof EventsIdRoute
  '/news/$id': typeof NewsIdRoute
  '/profile/upcoming': typeof ProfileUpcomingRoute
  '/admin': typeof AdminIndexRoute
  '/events': typeof EventsIndexRoute
  '/news': typeof NewsIndexRoute
  '/profile': typeof ProfileIndexRoute
  '/admin/events/new': typeof AdminEventsNewRoute
  '/admin/news/new': typeof AdminNewsNewRoute
  '/admin/applications': typeof AdminApplicationsIndexRoute
  '/admin/events': typeof AdminEventsIndexRoute
  '/admin/news': typeof AdminNewsIndexRoute
  '/admin/users': typeof AdminUsersIndexRoute
  '/admin/events/$id/edit': typeof AdminEventsIdEditRoute
  '/admin/news/$id/edit': typeof AdminNewsIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/$404': typeof R404Route
  '/sections': typeof SectionsRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/events/$id': typeof EventsIdRoute
  '/news/$id': typeof NewsIdRoute
  '/profile/upcoming': typeof ProfileUpcomingRoute
  '/admin/': typeof AdminIndexRoute
  '/events/': typeof EventsIndexRoute
  '/news/': typeof NewsIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/admin/events/new': typeof AdminEventsNewRoute
  '/admin/news/new': typeof AdminNewsNewRoute
  '/admin/applications/': typeof AdminApplicationsIndexRoute
  '/admin/events/': typeof AdminEventsIndexRoute
  '/admin/news/': typeof AdminNewsIndexRoute
  '/admin/users/': typeof AdminUsersIndexRoute
  '/admin/events/$id/edit': typeof AdminEventsIdEditRoute
  '/admin/news/$id/edit': typeof AdminNewsIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/$404'
    | '/sections'
    | '/auth/login'
    | '/auth/register'
    | '/events/$id'
    | '/news/$id'
    | '/profile/upcoming'
    | '/admin/'
    | '/events/'
    | '/news/'
    | '/profile/'
    | '/admin/events/new'
    | '/admin/news/new'
    | '/admin/applications/'
    | '/admin/events/'
    | '/admin/news/'
    | '/admin/users/'
    | '/admin/events/$id/edit'
    | '/admin/news/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$404'
    | '/sections'
    | '/auth/login'
    | '/auth/register'
    | '/events/$id'
    | '/news/$id'
    | '/profile/upcoming'
    | '/admin'
    | '/events'
    | '/news'
    | '/profile'
    | '/admin/events/new'
    | '/admin/news/new'
    | '/admin/applications'
    | '/admin/events'
    | '/admin/news'
    | '/admin/users'
    | '/admin/events/$id/edit'
    | '/admin/news/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/$404'
    | '/sections'
    | '/auth/login'
    | '/auth/register'
    | '/events/$id'
    | '/news/$id'
    | '/profile/upcoming'
    | '/admin/'
    | '/events/'
    | '/news/'
    | '/profile/'
    | '/admin/events/new'
    | '/admin/news/new'
    | '/admin/applications/'
    | '/admin/events/'
    | '/admin/news/'
    | '/admin/users/'
    | '/admin/events/$id/edit'
    | '/admin/news/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  R404Route: typeof R404Route
  SectionsRoute: typeof SectionsRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  EventsIdRoute: typeof EventsIdRoute
  NewsIdRoute: typeof NewsIdRoute
  ProfileUpcomingRoute: typeof ProfileUpcomingRoute
  EventsIndexRoute: typeof EventsIndexRoute
  NewsIndexRoute: typeof NewsIndexRoute
  ProfileIndexRoute: typeof ProfileIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sections': {
      id: '/sections'
      path: '/sections'
      fullPath: '/sections'
      preLoaderRoute: typeof SectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$404': {
      id: '/$404'
      path: '/$404'
      fullPath: '/$404'
      preLoaderRoute: typeof R404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/': {
      id: '/profile/'
      path: '/profile'
      fullPath: '/profile/'
      preLoaderRoute: typeof ProfileIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news/': {
      id: '/news/'
      path: '/news'
      fullPath: '/news/'
      preLoaderRoute: typeof NewsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/': {
      id: '/events/'
      path: '/events'
      fullPath: '/events/'
      preLoaderRoute: typeof EventsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/profile/upcoming': {
      id: '/profile/upcoming'
      path: '/profile/upcoming'
      fullPath: '/profile/upcoming'
      preLoaderRoute: typeof ProfileUpcomingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news/$id': {
      id: '/news/$id'
      path: '/news/$id'
      fullPath: '/news/$id'
      preLoaderRoute: typeof NewsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$id': {
      id: '/events/$id'
      path: '/events/$id'
      fullPath: '/events/$id'
      preLoaderRoute: typeof EventsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users/': {
      id: '/admin/users/'
      path: '/users'
      fullPath: '/admin/users/'
      preLoaderRoute: typeof AdminUsersIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/news/': {
      id: '/admin/news/'
      path: '/news'
      fullPath: '/admin/news/'
      preLoaderRoute: typeof AdminNewsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/events/': {
      id: '/admin/events/'
      path: '/events'
      fullPath: '/admin/events/'
      preLoaderRoute: typeof AdminEventsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/applications/': {
      id: '/admin/applications/'
      path: '/applications'
      fullPath: '/admin/applications/'
      preLoaderRoute: typeof AdminApplicationsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/news/new': {
      id: '/admin/news/new'
      path: '/news/new'
      fullPath: '/admin/news/new'
      preLoaderRoute: typeof AdminNewsNewRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/events/new': {
      id: '/admin/events/new'
      path: '/events/new'
      fullPath: '/admin/events/new'
      preLoaderRoute: typeof AdminEventsNewRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/news/$id/edit': {
      id: '/admin/news/$id/edit'
      path: '/news/$id/edit'
      fullPath: '/admin/news/$id/edit'
      preLoaderRoute: typeof AdminNewsIdEditRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/events/$id/edit': {
      id: '/admin/events/$id/edit'
      path: '/events/$id/edit'
      fullPath: '/admin/events/$id/edit'
      preLoaderRoute: typeof AdminEventsIdEditRouteImport
      parentRoute: typeof AdminRouteRoute
    }
  }
}

interface AdminRouteRouteChildren {
  AdminIndexRoute: typeof AdminIndexRoute
  AdminEventsNewRoute: typeof AdminEventsNewRoute
  AdminNewsNewRoute: typeof AdminNewsNewRoute
  AdminApplicationsIndexRoute: typeof AdminApplicationsIndexRoute
  AdminEventsIndexRoute: typeof AdminEventsIndexRoute
  AdminNewsIndexRoute: typeof AdminNewsIndexRoute
  AdminUsersIndexRoute: typeof AdminUsersIndexRoute
  AdminEventsIdEditRoute: typeof AdminEventsIdEditRoute
  AdminNewsIdEditRoute: typeof AdminNewsIdEditRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminIndexRoute: AdminIndexRoute,
  AdminEventsNewRoute: AdminEventsNewRoute,
  AdminNewsNewRoute: AdminNewsNewRoute,
  AdminApplicationsIndexRoute: AdminApplicationsIndexRoute,
  AdminEventsIndexRoute: AdminEventsIndexRoute,
  AdminNewsIndexRoute: AdminNewsIndexRoute,
  AdminUsersIndexRoute: AdminUsersIndexRoute,
  AdminEventsIdEditRoute: AdminEventsIdEditRoute,
  AdminNewsIdEditRoute: AdminNewsIdEditRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  R404Route: R404Route,
  SectionsRoute: SectionsRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  EventsIdRoute: EventsIdRoute,
  NewsIdRoute: NewsIdRoute,
  ProfileUpcomingRoute: ProfileUpcomingRoute,
  EventsIndexRoute: EventsIndexRoute,
  NewsIndexRoute: NewsIndexRoute,
  ProfileIndexRoute: ProfileIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
